### PR TITLE
Add x-compiler autodetect to Makefile & fix several issues

### LINKED ISSUE #13: Main's Makefile fails because of wrong name of asm compiler
- on main branch, after makefile MR, it tries to compile program with `riscv64-elf-gcc` while my pc (wsl, ubuntu) has `riscv64-unknown-elf-gcc` which may cause problems on other similar systems
- can be fixed by  `ln -s $(which riscv64-unknown-elf-gcc) /usr/local/bin/riscv64-elf-gcc` but ideally needs better fix

### PR DESCRIPTION
**Pull request by nerett**
Close #13

### CODE REVIEW

**Comment by vian96** [comment]
fails on my system
image

**Comment by nerett** [comment]
> fails on my system image
> 
> Line 3 indeed looks very weird: `IFS=":" read -ra paths <<< "$PATH"`

Ah shit here we go again

**Comment by vian96** [comment]
changed to using `command -v`. works for me please check if works for you. fixable by `ln -s` anyway so i'm merging

**Review by vian96 — APPROVED** [review]
lgtm

**Pull request merged**
